redis:
  image: redis:latest
  ports:
    - "6380:6379"

mongo:
  image: mongo:3.0.14
  ports:
    - "27018:27017"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .dev/mongo/:/data/db/
